---
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
template: |
  # Changelog

  $CHANGES

  ---

  See details of [all code changes](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION) since previous release.

categories:
  - title: ":warning: Breaking Changes"
    labels: d
      - "breaking change"
  - title: "ğŸš€ Features"
    labels:
      - "feature"
  - title: "ğŸ”§ Fixes"
    collapse-after: 3
    labels:
      - "fix"
  - title: "ğŸ“ Documentation"
    collapse-after: 3
    labels:
      - "documentation"
  - title: "ğŸ§ª Test"
    collapse-after: 3
    labels:
      - "test"
  - title: "âš™ï¸ CI/CD"
    collapse-after: 3
    labels:
      - "CI/CD"
  - title: "â™»ï¸ Refactor"
    collapse-after: 3
    labels:
      - "refactor"
  - title: "âš¡ Performance"
    collapse-after: 3
    labels:
      - "performance"
  - title: "ğŸ§¹ Chore"
    collapse-after: 3
    labels:
      - "chore"
  - title: "âª Revert"
    collapse-after: 3
    labels:
      - "revert"
  - title: "ğŸš§ WIP"
    collapse-after: 3
    labels:
      - "WIP"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"

version-resolver:
  major:
    labels:
      - "breaking change"
  minor:
    labels:
      - "feature"
  default: patch

exclude-labels:
  - "skip-changelog"
