name: Plan Terragrunt Environment in AWS

on:
  workflow_call:
    inputs:
      git_branch:
        description: "Branch triggering this plan"
        required: true
        type: string
      tf_version:
        description: "Version of Terraform to utilize"
        required: true
        default: "1.5.5"
        type: string
      tg_version:
        description: "Version of Terragrunt to utilize"
        required: true
        default: "0.54.11"
        type: string
      assume_role_arn:
        description: "ARN of the role to assume prior to Terragrunt invocation. Terragrunt may use this role to assume other roles if configured to do so."
        required: true
        type: string
      environments_root:
        description: "Root folder containing all environments"
        required: false
        default: "platform"
        type: string
      environment:
        description: "Environment (subfolder of environments_root, e.g. test) to plan"
        required: true
        type: string
      region:
        description: "Region within the environment (e.g. us-east-1) to plan"
        required: true
        type: string
      env_id:
        description: "Instance within the region (e.g. 000) to plan"
        required: true
        type: string
      before_plan_commands:
        description: "Commands to run prior to executing Terragrunt plan."
        required: false
        type: string
        default: ""
      after_plan_commands:
        description: "Commands to run after executing Terragrunt plan."
        required: false
        type: string
        default: ""

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: "Plan ${{ inputs.environment }}/${{ inputs.region }}/${{ inputs.env_id }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708
        with:
          role-to-assume: ${{ inputs.assume_role_arn }}
          role-session-name: ${{ github.run_id }}
          aws-region: ${{ inputs.region }}

      - name: "Set default Terraform Tags"
        id: set-tags
        run: |
          set -x
          echo "TF_VAR_organization_tag=${{ github.repository_owner }}" >> "$GITHUB_OUTPUT"
          echo "TF_VAR_repository_tag=$(echo "${{ github.repository }}" | cut -d "/" -f 2)" >> "$GITHUB_OUTPUT"
          echo "TF_VAR_commit_hash_tag=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          echo "TF_VAR_branch_tag=${{ inputs.git_branch }}" >> "$GITHUB_OUTPUT"

      - name: Configure Mise
        id: configure-mise
        uses: launchbynttdata/launch-workflows/.github/actions/terragrunt-configure-mise@fix/upgrade-terragrunt-action
        with:
          tf_version: ${{ inputs.tf_version }}
          tg_version: ${{ inputs.tg_version }}

      - name: Plan
        id: plan
        uses: gruntwork-io/terragrunt-action@5e86476ca61eaf74adb9c0525745f29f921f2199
        env:
          AWS_REGION: ${{ inputs.region }}
          INPUT_PRE_EXEC_0: |
            ${{ inputs.before_plan_commands }}
          INPUT_POST_EXEC_0: |
            ${{ inputs.after_plan_commands }}
          TF_VAR_organization_tag: ${{ steps.set-tags.outputs.TF_VAR_organization_tag }}
          TF_VAR_repository_tag: ${{ steps.set-tags.outputs.TF_VAR_repository_tag }}
          TF_VAR_commit_hash_tag: ${{ steps.set-tags.outputs.TF_VAR_commit_hash_tag }}
          TF_VAR_branch_tag: ${{ steps.set-tags.outputs.TF_VAR_branch_tag }}
        with:
          tf_path: "terraform"
          tg_version: ${{ inputs.tg_version }}
          tg_dir: "${{ inputs.environments_root }}/${{ inputs.environment }}/${{ inputs.region }}/${{ inputs.env_id }}"
          tg_command: "plan"
